language: node_js
node_js:
  - "4"
  - "6"
  - "node"
sudo: false

install:
  - travis_retry npm install --no-optional

script:
  - npm test

after_script:
  - travis_retry npm install coveralls codeclimate-test-reporter
  - cat coverage/lcov.info | node_modules/.bin/codeclimate-test-reporter
  - cat coverage/lcov.info | node_modules/.bin/coveralls
